name: Delete
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
      curl -L -X DELETE \
      -H "Accept: application/vnd.github+json" \
      -H "Authorization: Bearer <YOUR-TOKEN>"\
      -H "X-GitHub-Api-Version: 2022-11-28" \
       https://api.github.com/orgs/ORG/packages/PACKAGE_TYPE/PACKAGE_NAME
