name: Delete
on:
  workflow_dispatch:
  pull_request:
  
permissions: write-all  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: curl -L -X DELETE -H "Accept:application/vnd.github+json" -H "Authorization:Bearer ${{secrets.GITHUB_TOKEN}}" -H "X-GitHub-Api-Version:2022-11-28"  https://api.github.com/orgs/king-throne-7/packages/npm/package-example;
